import { Inter } from "next/font/google";
import { GoogleTagManager } from '@next/third-parties/google'
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Empreender Direito",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
